language: java

jdk:
  - openjdk7

before_script:
  - gem install heroku
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
script:
  - ./gradlew check
  - git remote add heroku git@heroku.com:tictaco-staging.git
  - export HEROKU_API_KEY=1781a65b-f739-4132-8c13-e44dbb59dd5a
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push heroku master
  - sleep 20s
  - ./gradlew seleniumXvfb

deploy:
  - provider: heroku
    api_key: "1781a65b-f739-4132-8c13-e44dbb59dd5a"
    strategy: git
    app:
      master: tictaco
