language: java

jdk:
  - openjdk7

env:
  global:
    - HEROKU_API_KEY=1781a65b-f739-4132-8c13-e44dbb59dd5a
    - HEROKU_STAGING_APP=tictaco-staging
    - GIT_REPO=TicTaCo
    - GIT_USER=HafdisE
    - GIT_TOKEN=e0b91f75ff50b97b3e6f2794b793e3e97ac1d12f

before_script:
  - gem install heroku
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config

script:
  - ./gradlew check
  - git remote add heroku git@heroku.com:$HEROKU_STAGING_APP.git
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push heroku master
  - sleep 20s
  - ./gradlew seleniumXvfb

after_success:
  - ./gradlew jacocoTestReport
  - ./bin/update-gh-pages

deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    strategy: git
    app:
      master: tictaco
