language: java
jdk:
- openjdk7
env:
  global:
  - HEROKU_STAGING_APP=tictaco-staging
  - GIT_REPO=TicTaCo
  - GIT_USER=HafdisE
  - secure: HyIzXv2iccD6JWGNgpk6yh0SuzJOg9x0qzF9rKfnOIUJSMlum0vPZbJ9/NJdrFJRaRA0/gsmP7cdzbGfZltgGi2Qsluso+GmPwhAaDU/5RWauEAR3c9Wf4OCZCSJa+imtK9bTHf7W/m3h7c6o3Hhi8YHoiSC9QQj2s27H+EcvSg=
  - secure: AwtCiWoYrEkS8/T0jQfdi8YYV9uv2puLWuFh6M2ZVy4VwAQ+3dDyzjkYiG6gecXIS3eaat0krjNPVLGdeeaJdvZeAaiYhWFi8qluJdP7AEVNGHTsh3Ru8Hhp2N/5eBIRZNhBxfuKVMMK2TKqnyWK7hGGMubNyLPyhTM8pjSElO8=

script:
- ./gradlew check && ./bin/stage && ./gradlew seleniumXvfb

after_script:
- ./gradlew test
- ./gradlew jacocoTestReport
- ./bin/update-gh-pages

deploy:
- provider: heroku
  api_key: $HEROKU_API_KEY
  strategy: git
  app:
    master: tictaco
