language: java

jdk:
  - openjdk7


script:
  - ./gradlew check
  - ./gradlew herokuAppDeploy
  - ./gradlew seleniumXvfb

deploy:
  - provider: heroku
    api_key: "1781a65b-f739-4132-8c13-e44dbb59dd5a"
    strategy: git
    app:
      master: tictaco
