language: java

jdk:
  - openjdk7

before_script:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

script:
  - ./gradlew check
  - ./bin/travis_staging
  - ./gradlew seleniumXvfb

deploy:
  - provider: heroku
    api_key: "1781a65b-f739-4132-8c13-e44dbb59dd5a"
    strategy: git
    app:
      master: tictaco
