language: java

jdk:
  - openjdk7

before_script:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - ./gradlew check
  - ./gradlew herokuAppDestroy
  - ./gradlew herokuAppCreate
  - yes | git push heroku master
  - sleep 20s
  - ./gradlew seleniumXvfb

deploy:
  - provider: heroku
    api_key: "1781a65b-f739-4132-8c13-e44dbb59dd5a"
    strategy: git
    app:
      master: tictaco
